// <auto-generated />
namespace MusicStore.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_thumnail_property_for_genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_thumnail_property_for_genre));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081515431_add_thumnail_property_for_genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
