// <auto-generated />
namespace MusicStore.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_isfeatured_property_for_album_artist_song : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isfeatured_property_for_album_artist_song));
        
        string IMigrationMetadata.Id
        {
            get { return "201805190826486_add_isfeatured_property_for_album_artist_song"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
