// <auto-generated />
namespace MusicStore.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_isfeatured_property_for_collection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isfeatured_property_for_collection));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210115086_add_isfeatured_property_for_collection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
