// <auto-generated />
namespace MusicStore.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_relationship_between_artist_genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_relationship_between_artist_genre));
        
        string IMigrationMetadata.Id
        {
            get { return "201805151436190_add_relationship_between_artist_genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
