// <auto-generated />
namespace MusicStore.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inittableandrelationshipforfreelandmanagementfeature : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inittableandrelationshipforfreelandmanagementfeature));
        
        string IMigrationMetadata.Id
        {
            get { return "201908170712205_Init table and relationship for freeland management feature"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
