// <auto-generated />
namespace MusicStore.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addPhotocolumninsystem_usertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPhotocolumninsystem_usertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201909130036349_add Photo column in system_user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
